name: RunicBank
version: ${project.version}
main: com.runicrealms.plugin.bank.RunicBank
api-version: 1.13
depend:
  - RunicCore
  - RunicRestart
  - RunicNpcs
  - RunicCommon
  - RunicDatabase
  - RunicItems
commands:
  runicbank:
    usage: /<commands>
    description: Opens the runic bank