name: RunicBank
version: ${project.version}
main: com.runicrealms.plugin.RunicBank
api-version: 1.13
depend: [RunicRestart]
commands:
  runicbank:
    usage: /<commands>
    description: Opens the runic bank